on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Buidld and Push to Azure Container Registry'
          uses: actions/checkout@main
          
      
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_SERVER }}
            username: ${{ secrets.ACR_USER }}
            password: ${{ secrets.ACR_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.ACR_SERVER }}/keengithub
            docker push ${{ secrets.ACR_SERVER }}/keengithub
